name: Build, Tag, and Deploy Docker Image

on:
  push:
    tags:
      - 'v*'  # only run on version tags like v1.0.0 , v2.3.4, etc.
    paths:
      - 'NOTIFICATION/**' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./NOTIFICATION
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/expo-push-server:latest
            ${{ secrets.DOCKER_USERNAME }}/expo-push-server:${{ steps.extract_version.outputs.VERSION }}

      - name: Trigger Render deploy hook
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}