name: Build, Tag, and Deploy Docker Image

on:
  push:
    # Trigger workflow on pushes to main branch or version tags like v1.0.0
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Extract version from tag or use short commit hash
      - name: Extract version or commit hash
        id: version
        run: |
          if [[ "$GITHUB_REF" == refs/tags/v* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          fi

      # Set up Docker Buildx for advanced build capabilities
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image with 'latest' and version/commit tags
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./NOTIFICATION
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/yup:latest
            ${{ secrets.DOCKER_USERNAME }}/yup:${{ steps.version.outputs.VERSION }}

      # Trigger Render deploy hook after Docker image is pushed
      - name: Trigger Render deploy hook
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}